### ISSUE TITLE
GLIBCXX_3.4.20

### ISSUE THREAD

**Issue by GabryOryn** [SaberMod/toolchain_manifest#4]
I have problem when compile cyanogenmod 12 with arm-linux-androideabi 4.8, the problem is: GLIBCXX_3.4.20.
How do I fix? thank you

**Comment by GabryOryn** [comment]
another problem:

error: array subscript is above array bounds [-Werror=array-bounds]
    f2[i] = f2[i] << 2;

**Comment by pbeeler** [comment]
You need to provide more output than that and on https://pastebin.com please.

**Comment by GabryOryn** [comment]
I solved the problem! For those who have the same problem, is the lack of some libraries.
sudo apt-get install libcloog-isl-dev

Thank you.

**Comment by pbeeler** [comment]
No you don't need those installed if you have a ROM patch thanks.

**Comment by siracuervo** [comment]
What rom patch?

**Comment by pbeeler** [comment]
GLIBCXX_3.4.20 is not related to the package libcloog-isl-dev

**Comment by siracuervo** [comment]
Im having same error compiling my rom based on AndroidOpenDevelopment...

**Comment by NoLimitSoldier** [comment]
@siracuervo Use LTS branch will solve your error.
https://github.com/SaberMod/arm-androideabi-4.8/tree/LTS

**Comment by siracuervo** [comment]
Thanks
